version: '3.8'

services:
  paddleocr-server:
    build: .
    container_name: ocr-server-fixed
    restart: unless-stopped
    
    ports:
      - "8501:8501"
    
    volumes:
      # Usar directorios con permisos correctos
      - ./data:/app/data
      - paddleocr-models:/app/.paddleocr
    
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
      # Variables para evitar problemas de permisos
      - PADDLE_HOME=/app/.paddleocr
      - MPLCONFIGDIR=/app/.matplotlib
    
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '4.0'
        reservations:
          memory: 3G
          cpus: '2.0'
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  paddleocr-models:
    driver: local
